Repository navdiya-nikunj/DSA-beginner-friendly, pull requests merged in 2022-10, with the labels that each got.

#3 Create Array.md
  DATA STRUCTURE/Array.md
Labels: documentation, good first issue

#6 Create linkedlist.md
  DATA STRUCTURE/linkedlist.md
Labels: documentation, Hactoberfest

#80 Create Counting_Sort.java
  ALGORITHMS/JAVA/Sorting/Counting_Sort.java
Labels: Hactoberfest

#77 Create Merge_Sort.java
  ALGORITHMS/JAVA/Sorting/Merge_Sort.java
Labels: Hactoberfest

#76 Create Insertion_Sort.java
  ALGORITHMS/JAVA/Sorting/Insertion_Sort.java
Labels: Hactoberfest

#84 Create quicksort.py
  ALGORITHMS/Python/Sorting/quicksort.py
Labels: Hactoberfest

#71 Kenil kanani patch 1
  DATA STRUCTURE/tree.md
Labels: Hactoberfest

#75 Created Heaps.md in DATA STRUCTURE folder
  DATA STRUCTURE/Heaps.md
Labels: Hactoberfest

#61 Create Selection_Sort.java
  ALGORITHMS/JAVA/Sorting/Selection_Sort.java
Labels: Hactoberfest

#91 selection_sort.c
  ALGORITHMS/C language/Sorting/selection_sort.c
Labels: Hactoberfest
